spring:
    jackson:
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
    main:
        allow-bean-definition-overriding: true
    security:
        user:
            name: disabled
            password: disabled

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,prometheus
    endpoint:
        health:
            show-details: always

logging:
    level:
        root: INFO
        org.springframework: INFO
    pattern:
        file: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %replace(%msg){'[\\r\\n]+',' '}%nopex%n"

resilience4j:
    circuitbreaker:
        configs:
            default:
                slidingWindowSize: 20
                minimumNumberOfCalls: 10
                failureRateThreshold: 50
                waitDurationInOpenState: 20s
    retry:
        configs:
            default:
                maxAttempts: 3
                waitDuration: 500ms
    bulkhead:
        configs:
            default:
                maxConcurrentCalls: 50
                maxWaitDuration: 0
    ratelimiter:
        configs:
            default:
                limitForPeriod: 10
                limitRefreshPeriod: 60s
                timeoutDuration: 0
