server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: auth-service
  security:
    user:
      name: disabled
      password: disabled

  # data:
  mongodb:
    uri: ${MONGO_AUTH_URI:mongodb+srv://rahulray:W5hmMtw9vpG7vYkY@cluster0.z15xp0c.mongodb.net/authdb?authSource=admin}

# security:
jwt:
  secret: ${JWT_SECRET:MyJwtSecretKey12345678901234567890}
  accessTokenExpiration: 900        # 15 min
  refreshTokenExpiration: 7    # 7 days
  issuer: auth-service
  audience: product-journey-platform

logging:
  level:
    root: DEBUG
