server:
  port: ${SERVER_PORT:8080}
spring:
  # data:
  mongodb:
    uri: ${MONGO_JOURNEY_URI}

journey:
  metadata:
    source: database   # database | json | excel
  pricing:
    engine-enabled: true
  underwriting:
    enabled: true
  validation:
    dynamic-rules: true