server:
  port: 80
spring:
  # data:
  mongodb:
    uri: ${MONGO_JOURNEY_URI:mongodb+srv://rahulray:W5hmMtw9vpG7vYkY@cluster0.z15xp0c.mongodb.net/unifiedJourney?authSource=admin}

journey:
  metadata:
    source: database   # database | json | excel
  pricing:
    engine-enabled: true
  underwriting:
    enabled: true
  validation:
    dynamic-rules: true