server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: user-service

  # data:
  mongodb:
    uri: ${MONGO_USER_URI:mongodb+srv://rahulray:W5hmMtw9vpG7vYkY@cluster0.z15xp0c.mongodb.net/authdb?authSource=admin}
