server:
  port: ${SERVER_PORT:8082}
service:
  auth:
    url: ${AUTH_SERVICE_URL:http://localhost:8083}
    
spring:
  data:
    mongodb:
      uri: ${MONGO_USER_URI:mongodb+srv://rahulray:W5hmMtw9vpG7vYkY@cluster0.z15xp0c.mongodb.net/authdb?authSource=admin}

logging:
  level:
    root: INFO
