server:
  port: ${SERVER_PORT:8079}

spring:
  application:
    name: bff-service

services:
  auth:
    url: ${AUTH_SERVICE_URL:3.229.131.115:8083}
  user:
    url: ${CORE_SERVICE_URL:3.229.131.115:8081}
  journey:
    url: ${HOURNEY_SERVICE_URL:3.229.131.115:8081}
  document:
    url: http://document-service:8084

bff:
  parallel-calls:
    enabled: true
  timeout:
    connect: 3s
    read: 5s

cors:
  allowed-origins: "*"
  allowed-methods: GET,POST,PUT,DELETE