server:
  port: 8080

spring:
  application:
    name: bff-service

services:
  auth:
    url: http://auth-service:8081
  user:
    url: http://user-service:8082
  journey:
    url: http://journey-service:8083
  document:
    url: http://document-service:8084

bff:
  parallel-calls:
    enabled: true
  timeout:
    connect: 3s
    read: 5s

cors:
  allowed-origins: "*"
  allowed-methods: GET,POST,PUT,DELETE